// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: proto/lightnet.proto

package lightnet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HashService_SubmitHash_FullMethodName        = "/lightnet.HashService/SubmitHash"
	HashService_SubmitHashStream_FullMethodName  = "/lightnet.HashService/SubmitHashStream"
	HashService_DebugHash_FullMethodName         = "/lightnet.HashService/DebugHash"
	HashService_GetDatabaseStats_FullMethodName  = "/lightnet.HashService/GetDatabaseStats"
	HashService_GetRecord_FullMethodName         = "/lightnet.HashService/GetRecord"
	HashService_GetMerkleProof_FullMethodName    = "/lightnet.HashService/GetMerkleProof"
	HashService_GetMerkleRoot_FullMethodName     = "/lightnet.HashService/GetMerkleRoot"
	HashService_VerifyMerkleProof_FullMethodName = "/lightnet.HashService/VerifyMerkleProof"
)

// HashServiceClient is the client API for HashService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HashServiceClient interface {
	SubmitHash(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error)
	SubmitHashStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HashRequest, HashResponse], error)
	DebugHash(ctx context.Context, in *DebugHashRequest, opts ...grpc.CallOption) (*DebugHashResponse, error)
	GetDatabaseStats(ctx context.Context, in *DatabaseStatsRequest, opts ...grpc.CallOption) (*DatabaseStatsResponse, error)
	GetRecord(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*GetRecordResponse, error)
	GetMerkleProof(ctx context.Context, in *MerkleProofRequest, opts ...grpc.CallOption) (*MerkleProofResponse, error)
	GetMerkleRoot(ctx context.Context, in *MerkleRootRequest, opts ...grpc.CallOption) (*MerkleRootResponse, error)
	VerifyMerkleProof(ctx context.Context, in *VerifyMerkleProofRequest, opts ...grpc.CallOption) (*VerifyMerkleProofResponse, error)
}

type hashServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHashServiceClient(cc grpc.ClientConnInterface) HashServiceClient {
	return &hashServiceClient{cc}
}

func (c *hashServiceClient) SubmitHash(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashResponse)
	err := c.cc.Invoke(ctx, HashService_SubmitHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashServiceClient) SubmitHashStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HashRequest, HashResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HashService_ServiceDesc.Streams[0], HashService_SubmitHashStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HashRequest, HashResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HashService_SubmitHashStreamClient = grpc.BidiStreamingClient[HashRequest, HashResponse]

func (c *hashServiceClient) DebugHash(ctx context.Context, in *DebugHashRequest, opts ...grpc.CallOption) (*DebugHashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DebugHashResponse)
	err := c.cc.Invoke(ctx, HashService_DebugHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashServiceClient) GetDatabaseStats(ctx context.Context, in *DatabaseStatsRequest, opts ...grpc.CallOption) (*DatabaseStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DatabaseStatsResponse)
	err := c.cc.Invoke(ctx, HashService_GetDatabaseStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashServiceClient) GetRecord(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*GetRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecordResponse)
	err := c.cc.Invoke(ctx, HashService_GetRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashServiceClient) GetMerkleProof(ctx context.Context, in *MerkleProofRequest, opts ...grpc.CallOption) (*MerkleProofResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MerkleProofResponse)
	err := c.cc.Invoke(ctx, HashService_GetMerkleProof_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashServiceClient) GetMerkleRoot(ctx context.Context, in *MerkleRootRequest, opts ...grpc.CallOption) (*MerkleRootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MerkleRootResponse)
	err := c.cc.Invoke(ctx, HashService_GetMerkleRoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashServiceClient) VerifyMerkleProof(ctx context.Context, in *VerifyMerkleProofRequest, opts ...grpc.CallOption) (*VerifyMerkleProofResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyMerkleProofResponse)
	err := c.cc.Invoke(ctx, HashService_VerifyMerkleProof_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HashServiceServer is the server API for HashService service.
// All implementations must embed UnimplementedHashServiceServer
// for forward compatibility.
type HashServiceServer interface {
	SubmitHash(context.Context, *HashRequest) (*HashResponse, error)
	SubmitHashStream(grpc.BidiStreamingServer[HashRequest, HashResponse]) error
	DebugHash(context.Context, *DebugHashRequest) (*DebugHashResponse, error)
	GetDatabaseStats(context.Context, *DatabaseStatsRequest) (*DatabaseStatsResponse, error)
	GetRecord(context.Context, *GetRecordRequest) (*GetRecordResponse, error)
	GetMerkleProof(context.Context, *MerkleProofRequest) (*MerkleProofResponse, error)
	GetMerkleRoot(context.Context, *MerkleRootRequest) (*MerkleRootResponse, error)
	VerifyMerkleProof(context.Context, *VerifyMerkleProofRequest) (*VerifyMerkleProofResponse, error)
	mustEmbedUnimplementedHashServiceServer()
}

// UnimplementedHashServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHashServiceServer struct{}

func (UnimplementedHashServiceServer) SubmitHash(context.Context, *HashRequest) (*HashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitHash not implemented")
}
func (UnimplementedHashServiceServer) SubmitHashStream(grpc.BidiStreamingServer[HashRequest, HashResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SubmitHashStream not implemented")
}
func (UnimplementedHashServiceServer) DebugHash(context.Context, *DebugHashRequest) (*DebugHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DebugHash not implemented")
}
func (UnimplementedHashServiceServer) GetDatabaseStats(context.Context, *DatabaseStatsRequest) (*DatabaseStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDatabaseStats not implemented")
}
func (UnimplementedHashServiceServer) GetRecord(context.Context, *GetRecordRequest) (*GetRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecord not implemented")
}
func (UnimplementedHashServiceServer) GetMerkleProof(context.Context, *MerkleProofRequest) (*MerkleProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMerkleProof not implemented")
}
func (UnimplementedHashServiceServer) GetMerkleRoot(context.Context, *MerkleRootRequest) (*MerkleRootResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMerkleRoot not implemented")
}
func (UnimplementedHashServiceServer) VerifyMerkleProof(context.Context, *VerifyMerkleProofRequest) (*VerifyMerkleProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyMerkleProof not implemented")
}
func (UnimplementedHashServiceServer) mustEmbedUnimplementedHashServiceServer() {}
func (UnimplementedHashServiceServer) testEmbeddedByValue()                     {}

// UnsafeHashServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HashServiceServer will
// result in compilation errors.
type UnsafeHashServiceServer interface {
	mustEmbedUnimplementedHashServiceServer()
}

func RegisterHashServiceServer(s grpc.ServiceRegistrar, srv HashServiceServer) {
	// If the following call pancis, it indicates UnimplementedHashServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HashService_ServiceDesc, srv)
}

func _HashService_SubmitHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashServiceServer).SubmitHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashService_SubmitHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashServiceServer).SubmitHash(ctx, req.(*HashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashService_SubmitHashStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HashServiceServer).SubmitHashStream(&grpc.GenericServerStream[HashRequest, HashResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HashService_SubmitHashStreamServer = grpc.BidiStreamingServer[HashRequest, HashResponse]

func _HashService_DebugHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DebugHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashServiceServer).DebugHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashService_DebugHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashServiceServer).DebugHash(ctx, req.(*DebugHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashService_GetDatabaseStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatabaseStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashServiceServer).GetDatabaseStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashService_GetDatabaseStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashServiceServer).GetDatabaseStats(ctx, req.(*DatabaseStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashService_GetRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashServiceServer).GetRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashService_GetRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashServiceServer).GetRecord(ctx, req.(*GetRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashService_GetMerkleProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerkleProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashServiceServer).GetMerkleProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashService_GetMerkleProof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashServiceServer).GetMerkleProof(ctx, req.(*MerkleProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashService_GetMerkleRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerkleRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashServiceServer).GetMerkleRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashService_GetMerkleRoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashServiceServer).GetMerkleRoot(ctx, req.(*MerkleRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashService_VerifyMerkleProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyMerkleProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashServiceServer).VerifyMerkleProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashService_VerifyMerkleProof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashServiceServer).VerifyMerkleProof(ctx, req.(*VerifyMerkleProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HashService_ServiceDesc is the grpc.ServiceDesc for HashService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HashService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lightnet.HashService",
	HandlerType: (*HashServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitHash",
			Handler:    _HashService_SubmitHash_Handler,
		},
		{
			MethodName: "DebugHash",
			Handler:    _HashService_DebugHash_Handler,
		},
		{
			MethodName: "GetDatabaseStats",
			Handler:    _HashService_GetDatabaseStats_Handler,
		},
		{
			MethodName: "GetRecord",
			Handler:    _HashService_GetRecord_Handler,
		},
		{
			MethodName: "GetMerkleProof",
			Handler:    _HashService_GetMerkleProof_Handler,
		},
		{
			MethodName: "GetMerkleRoot",
			Handler:    _HashService_GetMerkleRoot_Handler,
		},
		{
			MethodName: "VerifyMerkleProof",
			Handler:    _HashService_VerifyMerkleProof_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubmitHashStream",
			Handler:       _HashService_SubmitHashStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/lightnet.proto",
}
