// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.20.3
// source: proto/lightnet.proto

package lightnet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataType      []byte                 `protobuf:"bytes,1,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"` // Must be exactly 32 bytes
	DataItem      []byte                 `protobuf:"bytes,2,opt,name=data_item,json=dataItem,proto3" json:"data_item,omitempty"` // Must be exactly 32 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashRequest) Reset() {
	*x = HashRequest{}
	mi := &file_proto_lightnet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashRequest) ProtoMessage() {}

func (x *HashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lightnet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashRequest.ProtoReflect.Descriptor instead.
func (*HashRequest) Descriptor() ([]byte, []int) {
	return file_proto_lightnet_proto_rawDescGZIP(), []int{0}
}

func (x *HashRequest) GetDataType() []byte {
	if x != nil {
		return x.DataType
	}
	return nil
}

func (x *HashRequest) GetDataItem() []byte {
	if x != nil {
		return x.DataItem
	}
	return nil
}

type HashResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ComputedHashHex string                 `protobuf:"bytes,3,opt,name=computed_hash_hex,json=computedHashHex,proto3" json:"computed_hash_hex,omitempty"` // The computed hash as hex string
	TimeuuidHex     string                 `protobuf:"bytes,4,opt,name=timeuuid_hex,json=timeuuidHex,proto3" json:"timeuuid_hex,omitempty"`               // TimeUUID as hex string
	DataTypeHex     string                 `protobuf:"bytes,5,opt,name=data_type_hex,json=dataTypeHex,proto3" json:"data_type_hex,omitempty"`             // data_type as hex string (echoed back)
	DataItemHex     string                 `protobuf:"bytes,6,opt,name=data_item_hex,json=dataItemHex,proto3" json:"data_item_hex,omitempty"`             // data_item as hex string (echoed back)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HashResponse) Reset() {
	*x = HashResponse{}
	mi := &file_proto_lightnet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashResponse) ProtoMessage() {}

func (x *HashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lightnet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashResponse.ProtoReflect.Descriptor instead.
func (*HashResponse) Descriptor() ([]byte, []int) {
	return file_proto_lightnet_proto_rawDescGZIP(), []int{1}
}

func (x *HashResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HashResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HashResponse) GetComputedHashHex() string {
	if x != nil {
		return x.ComputedHashHex
	}
	return ""
}

func (x *HashResponse) GetTimeuuidHex() string {
	if x != nil {
		return x.TimeuuidHex
	}
	return ""
}

func (x *HashResponse) GetDataTypeHex() string {
	if x != nil {
		return x.DataTypeHex
	}
	return ""
}

func (x *HashResponse) GetDataItemHex() string {
	if x != nil {
		return x.DataItemHex
	}
	return ""
}

type DebugHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataType      []byte                 `protobuf:"bytes,1,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"` // Must be exactly 32 bytes
	DataItem      []byte                 `protobuf:"bytes,2,opt,name=data_item,json=dataItem,proto3" json:"data_item,omitempty"` // Must be exactly 32 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugHashRequest) Reset() {
	*x = DebugHashRequest{}
	mi := &file_proto_lightnet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugHashRequest) ProtoMessage() {}

func (x *DebugHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lightnet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugHashRequest.ProtoReflect.Descriptor instead.
func (*DebugHashRequest) Descriptor() ([]byte, []int) {
	return file_proto_lightnet_proto_rawDescGZIP(), []int{2}
}

func (x *DebugHashRequest) GetDataType() []byte {
	if x != nil {
		return x.DataType
	}
	return nil
}

func (x *DebugHashRequest) GetDataItem() []byte {
	if x != nil {
		return x.DataItem
	}
	return nil
}

type DebugHashResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	HashInputHex    string                 `protobuf:"bytes,3,opt,name=hash_input_hex,json=hashInputHex,proto3" json:"hash_input_hex,omitempty"`
	ComputedHashHex string                 `protobuf:"bytes,4,opt,name=computed_hash_hex,json=computedHashHex,proto3" json:"computed_hash_hex,omitempty"`
	PrevHashHex     string                 `protobuf:"bytes,5,opt,name=prev_hash_hex,json=prevHashHex,proto3" json:"prev_hash_hex,omitempty"`
	UuidHex         string                 `protobuf:"bytes,6,opt,name=uuid_hex,json=uuidHex,proto3" json:"uuid_hex,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DebugHashResponse) Reset() {
	*x = DebugHashResponse{}
	mi := &file_proto_lightnet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugHashResponse) ProtoMessage() {}

func (x *DebugHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lightnet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugHashResponse.ProtoReflect.Descriptor instead.
func (*DebugHashResponse) Descriptor() ([]byte, []int) {
	return file_proto_lightnet_proto_rawDescGZIP(), []int{3}
}

func (x *DebugHashResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DebugHashResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DebugHashResponse) GetHashInputHex() string {
	if x != nil {
		return x.HashInputHex
	}
	return ""
}

func (x *DebugHashResponse) GetComputedHashHex() string {
	if x != nil {
		return x.ComputedHashHex
	}
	return ""
}

func (x *DebugHashResponse) GetPrevHashHex() string {
	if x != nil {
		return x.PrevHashHex
	}
	return ""
}

func (x *DebugHashResponse) GetUuidHex() string {
	if x != nil {
		return x.UuidHex
	}
	return ""
}

type DatabaseStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseStatsRequest) Reset() {
	*x = DatabaseStatsRequest{}
	mi := &file_proto_lightnet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseStatsRequest) ProtoMessage() {}

func (x *DatabaseStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lightnet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseStatsRequest.ProtoReflect.Descriptor instead.
func (*DatabaseStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_lightnet_proto_rawDescGZIP(), []int{4}
}

type DatabaseStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TotalRecords  int64                  `protobuf:"varint,3,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseStatsResponse) Reset() {
	*x = DatabaseStatsResponse{}
	mi := &file_proto_lightnet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseStatsResponse) ProtoMessage() {}

func (x *DatabaseStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lightnet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseStatsResponse.ProtoReflect.Descriptor instead.
func (*DatabaseStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_lightnet_proto_rawDescGZIP(), []int{5}
}

func (x *DatabaseStatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DatabaseStatsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DatabaseStatsResponse) GetTotalRecords() int64 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

type GetRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataType      []byte                 `protobuf:"bytes,1,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"` // Must be exactly 32 bytes
	DataItem      []byte                 `protobuf:"bytes,2,opt,name=data_item,json=dataItem,proto3" json:"data_item,omitempty"` // Must be exactly 32 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordRequest) Reset() {
	*x = GetRecordRequest{}
	mi := &file_proto_lightnet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordRequest) ProtoMessage() {}

func (x *GetRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lightnet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordRequest.ProtoReflect.Descriptor instead.
func (*GetRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_lightnet_proto_rawDescGZIP(), []int{6}
}

func (x *GetRecordRequest) GetDataType() []byte {
	if x != nil {
		return x.DataType
	}
	return nil
}

func (x *GetRecordRequest) GetDataItem() []byte {
	if x != nil {
		return x.DataItem
	}
	return nil
}

type GetRecordResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Record data (only present if success = true)
	UuidHex       string `protobuf:"bytes,3,opt,name=uuid_hex,json=uuidHex,proto3" json:"uuid_hex,omitempty"`               // TimeUUID as hex string
	DataTypeHex   string `protobuf:"bytes,4,opt,name=data_type_hex,json=dataTypeHex,proto3" json:"data_type_hex,omitempty"` // data_type as hex string
	DataItemHex   string `protobuf:"bytes,5,opt,name=data_item_hex,json=dataItemHex,proto3" json:"data_item_hex,omitempty"` // data_item as hex string
	HashItemHex   string `protobuf:"bytes,6,opt,name=hash_item_hex,json=hashItemHex,proto3" json:"hash_item_hex,omitempty"` // computed hash as hex string
	Timestamp     string `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                          // timestamp in ISO format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordResponse) Reset() {
	*x = GetRecordResponse{}
	mi := &file_proto_lightnet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordResponse) ProtoMessage() {}

func (x *GetRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lightnet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordResponse.ProtoReflect.Descriptor instead.
func (*GetRecordResponse) Descriptor() ([]byte, []int) {
	return file_proto_lightnet_proto_rawDescGZIP(), []int{7}
}

func (x *GetRecordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetRecordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetRecordResponse) GetUuidHex() string {
	if x != nil {
		return x.UuidHex
	}
	return ""
}

func (x *GetRecordResponse) GetDataTypeHex() string {
	if x != nil {
		return x.DataTypeHex
	}
	return ""
}

func (x *GetRecordResponse) GetDataItemHex() string {
	if x != nil {
		return x.DataItemHex
	}
	return ""
}

func (x *GetRecordResponse) GetHashItemHex() string {
	if x != nil {
		return x.HashItemHex
	}
	return ""
}

func (x *GetRecordResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// Merkle proof messages
type MerkleProofRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HashPosition  int64                  `protobuf:"varint,1,opt,name=hash_position,json=hashPosition,proto3" json:"hash_position,omitempty"` // Position of the hash in the sequence
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleProofRequest) Reset() {
	*x = MerkleProofRequest{}
	mi := &file_proto_lightnet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleProofRequest) ProtoMessage() {}

func (x *MerkleProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lightnet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleProofRequest.ProtoReflect.Descriptor instead.
func (*MerkleProofRequest) Descriptor() ([]byte, []int) {
	return file_proto_lightnet_proto_rawDescGZIP(), []int{8}
}

func (x *MerkleProofRequest) GetHashPosition() int64 {
	if x != nil {
		return x.HashPosition
	}
	return 0
}

type MerkleProofResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ProofHashesHex []string               `protobuf:"bytes,3,rep,name=proof_hashes_hex,json=proofHashesHex,proto3" json:"proof_hashes_hex,omitempty"` // Array of sibling hashes as hex strings
	Levels         int32                  `protobuf:"varint,4,opt,name=levels,proto3" json:"levels,omitempty"`                                        // Number of levels in the proof
	Position       int64                  `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`                                    // Original position of the hash
	RootHashHex    string                 `protobuf:"bytes,6,opt,name=root_hash_hex,json=rootHashHex,proto3" json:"root_hash_hex,omitempty"`          // Computed root hash from proof hashes
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MerkleProofResponse) Reset() {
	*x = MerkleProofResponse{}
	mi := &file_proto_lightnet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleProofResponse) ProtoMessage() {}

func (x *MerkleProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lightnet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleProofResponse.ProtoReflect.Descriptor instead.
func (*MerkleProofResponse) Descriptor() ([]byte, []int) {
	return file_proto_lightnet_proto_rawDescGZIP(), []int{9}
}

func (x *MerkleProofResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MerkleProofResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MerkleProofResponse) GetProofHashesHex() []string {
	if x != nil {
		return x.ProofHashesHex
	}
	return nil
}

func (x *MerkleProofResponse) GetLevels() int32 {
	if x != nil {
		return x.Levels
	}
	return 0
}

func (x *MerkleProofResponse) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *MerkleProofResponse) GetRootHashHex() string {
	if x != nil {
		return x.RootHashHex
	}
	return ""
}

type MerkleRootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleRootRequest) Reset() {
	*x = MerkleRootRequest{}
	mi := &file_proto_lightnet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleRootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleRootRequest) ProtoMessage() {}

func (x *MerkleRootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lightnet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleRootRequest.ProtoReflect.Descriptor instead.
func (*MerkleRootRequest) Descriptor() ([]byte, []int) {
	return file_proto_lightnet_proto_rawDescGZIP(), []int{10}
}

type MerkleRootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RootHashHex   string                 `protobuf:"bytes,3,opt,name=root_hash_hex,json=rootHashHex,proto3" json:"root_hash_hex,omitempty"`   // Current merkle root as hex string
	TotalRecords  int64                  `protobuf:"varint,4,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"` // Total number of records in the tree
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleRootResponse) Reset() {
	*x = MerkleRootResponse{}
	mi := &file_proto_lightnet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleRootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleRootResponse) ProtoMessage() {}

func (x *MerkleRootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lightnet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleRootResponse.ProtoReflect.Descriptor instead.
func (*MerkleRootResponse) Descriptor() ([]byte, []int) {
	return file_proto_lightnet_proto_rawDescGZIP(), []int{11}
}

func (x *MerkleRootResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MerkleRootResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MerkleRootResponse) GetRootHashHex() string {
	if x != nil {
		return x.RootHashHex
	}
	return ""
}

func (x *MerkleRootResponse) GetTotalRecords() int64 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

type VerifyMerkleProofRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetHashHex  string                 `protobuf:"bytes,1,opt,name=target_hash_hex,json=targetHashHex,proto3" json:"target_hash_hex,omitempty"`    // The hash to verify (32 bytes as hex)
	ProofHashesHex []string               `protobuf:"bytes,2,rep,name=proof_hashes_hex,json=proofHashesHex,proto3" json:"proof_hashes_hex,omitempty"` // Array of sibling hashes as hex strings
	Levels         int32                  `protobuf:"varint,3,opt,name=levels,proto3" json:"levels,omitempty"`                                        // Number of levels in the proof
	Position       int64                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`                                    // Position of the hash in the sequence
	RootHashHex    string                 `protobuf:"bytes,5,opt,name=root_hash_hex,json=rootHashHex,proto3" json:"root_hash_hex,omitempty"`          // Expected root hash as hex string
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyMerkleProofRequest) Reset() {
	*x = VerifyMerkleProofRequest{}
	mi := &file_proto_lightnet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyMerkleProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyMerkleProofRequest) ProtoMessage() {}

func (x *VerifyMerkleProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lightnet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyMerkleProofRequest.ProtoReflect.Descriptor instead.
func (*VerifyMerkleProofRequest) Descriptor() ([]byte, []int) {
	return file_proto_lightnet_proto_rawDescGZIP(), []int{12}
}

func (x *VerifyMerkleProofRequest) GetTargetHashHex() string {
	if x != nil {
		return x.TargetHashHex
	}
	return ""
}

func (x *VerifyMerkleProofRequest) GetProofHashesHex() []string {
	if x != nil {
		return x.ProofHashesHex
	}
	return nil
}

func (x *VerifyMerkleProofRequest) GetLevels() int32 {
	if x != nil {
		return x.Levels
	}
	return 0
}

func (x *VerifyMerkleProofRequest) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *VerifyMerkleProofRequest) GetRootHashHex() string {
	if x != nil {
		return x.RootHashHex
	}
	return ""
}

type VerifyMerkleProofResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	IsValid       bool                   `protobuf:"varint,3,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"` // Whether the proof is valid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyMerkleProofResponse) Reset() {
	*x = VerifyMerkleProofResponse{}
	mi := &file_proto_lightnet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyMerkleProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyMerkleProofResponse) ProtoMessage() {}

func (x *VerifyMerkleProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lightnet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyMerkleProofResponse.ProtoReflect.Descriptor instead.
func (*VerifyMerkleProofResponse) Descriptor() ([]byte, []int) {
	return file_proto_lightnet_proto_rawDescGZIP(), []int{13}
}

func (x *VerifyMerkleProofResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VerifyMerkleProofResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VerifyMerkleProofResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

var File_proto_lightnet_proto protoreflect.FileDescriptor

const file_proto_lightnet_proto_rawDesc = "" +
	"\n" +
	"\x14proto/lightnet.proto\x12\blightnet\"G\n" +
	"\vHashRequest\x12\x1b\n" +
	"\tdata_type\x18\x01 \x01(\fR\bdataType\x12\x1b\n" +
	"\tdata_item\x18\x02 \x01(\fR\bdataItem\"\xd9\x01\n" +
	"\fHashResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x11computed_hash_hex\x18\x03 \x01(\tR\x0fcomputedHashHex\x12!\n" +
	"\ftimeuuid_hex\x18\x04 \x01(\tR\vtimeuuidHex\x12\"\n" +
	"\rdata_type_hex\x18\x05 \x01(\tR\vdataTypeHex\x12\"\n" +
	"\rdata_item_hex\x18\x06 \x01(\tR\vdataItemHex\"L\n" +
	"\x10DebugHashRequest\x12\x1b\n" +
	"\tdata_type\x18\x01 \x01(\fR\bdataType\x12\x1b\n" +
	"\tdata_item\x18\x02 \x01(\fR\bdataItem\"\xd8\x01\n" +
	"\x11DebugHashResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\x0ehash_input_hex\x18\x03 \x01(\tR\fhashInputHex\x12*\n" +
	"\x11computed_hash_hex\x18\x04 \x01(\tR\x0fcomputedHashHex\x12\"\n" +
	"\rprev_hash_hex\x18\x05 \x01(\tR\vprevHashHex\x12\x19\n" +
	"\buuid_hex\x18\x06 \x01(\tR\auuidHex\"\x16\n" +
	"\x14DatabaseStatsRequest\"p\n" +
	"\x15DatabaseStatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rtotal_records\x18\x03 \x01(\x03R\ftotalRecords\"L\n" +
	"\x10GetRecordRequest\x12\x1b\n" +
	"\tdata_type\x18\x01 \x01(\fR\bdataType\x12\x1b\n" +
	"\tdata_item\x18\x02 \x01(\fR\bdataItem\"\xec\x01\n" +
	"\x11GetRecordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\buuid_hex\x18\x03 \x01(\tR\auuidHex\x12\"\n" +
	"\rdata_type_hex\x18\x04 \x01(\tR\vdataTypeHex\x12\"\n" +
	"\rdata_item_hex\x18\x05 \x01(\tR\vdataItemHex\x12\"\n" +
	"\rhash_item_hex\x18\x06 \x01(\tR\vhashItemHex\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\"9\n" +
	"\x12MerkleProofRequest\x12#\n" +
	"\rhash_position\x18\x01 \x01(\x03R\fhashPosition\"\xcb\x01\n" +
	"\x13MerkleProofResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x10proof_hashes_hex\x18\x03 \x03(\tR\x0eproofHashesHex\x12\x16\n" +
	"\x06levels\x18\x04 \x01(\x05R\x06levels\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\x03R\bposition\x12\"\n" +
	"\rroot_hash_hex\x18\x06 \x01(\tR\vrootHashHex\"\x13\n" +
	"\x11MerkleRootRequest\"\x91\x01\n" +
	"\x12MerkleRootResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\"\n" +
	"\rroot_hash_hex\x18\x03 \x01(\tR\vrootHashHex\x12#\n" +
	"\rtotal_records\x18\x04 \x01(\x03R\ftotalRecords\"\xc4\x01\n" +
	"\x18VerifyMerkleProofRequest\x12&\n" +
	"\x0ftarget_hash_hex\x18\x01 \x01(\tR\rtargetHashHex\x12(\n" +
	"\x10proof_hashes_hex\x18\x02 \x03(\tR\x0eproofHashesHex\x12\x16\n" +
	"\x06levels\x18\x03 \x01(\x05R\x06levels\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x03R\bposition\x12\"\n" +
	"\rroot_hash_hex\x18\x05 \x01(\tR\vrootHashHex\"j\n" +
	"\x19VerifyMerkleProofResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bis_valid\x18\x03 \x01(\bR\aisValid2\xeb\x04\n" +
	"\vHashService\x12;\n" +
	"\n" +
	"SubmitHash\x12\x15.lightnet.HashRequest\x1a\x16.lightnet.HashResponse\x12E\n" +
	"\x10SubmitHashStream\x12\x15.lightnet.HashRequest\x1a\x16.lightnet.HashResponse(\x010\x01\x12D\n" +
	"\tDebugHash\x12\x1a.lightnet.DebugHashRequest\x1a\x1b.lightnet.DebugHashResponse\x12S\n" +
	"\x10GetDatabaseStats\x12\x1e.lightnet.DatabaseStatsRequest\x1a\x1f.lightnet.DatabaseStatsResponse\x12D\n" +
	"\tGetRecord\x12\x1a.lightnet.GetRecordRequest\x1a\x1b.lightnet.GetRecordResponse\x12M\n" +
	"\x0eGetMerkleProof\x12\x1c.lightnet.MerkleProofRequest\x1a\x1d.lightnet.MerkleProofResponse\x12J\n" +
	"\rGetMerkleRoot\x12\x1b.lightnet.MerkleRootRequest\x1a\x1c.lightnet.MerkleRootResponse\x12\\\n" +
	"\x11VerifyMerkleProof\x12\".lightnet.VerifyMerkleProofRequest\x1a#.lightnet.VerifyMerkleProofResponseB\x12Z\x10./proto/lightnetb\x06proto3"

var (
	file_proto_lightnet_proto_rawDescOnce sync.Once
	file_proto_lightnet_proto_rawDescData []byte
)

func file_proto_lightnet_proto_rawDescGZIP() []byte {
	file_proto_lightnet_proto_rawDescOnce.Do(func() {
		file_proto_lightnet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lightnet_proto_rawDesc), len(file_proto_lightnet_proto_rawDesc)))
	})
	return file_proto_lightnet_proto_rawDescData
}

var file_proto_lightnet_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_lightnet_proto_goTypes = []any{
	(*HashRequest)(nil),               // 0: lightnet.HashRequest
	(*HashResponse)(nil),              // 1: lightnet.HashResponse
	(*DebugHashRequest)(nil),          // 2: lightnet.DebugHashRequest
	(*DebugHashResponse)(nil),         // 3: lightnet.DebugHashResponse
	(*DatabaseStatsRequest)(nil),      // 4: lightnet.DatabaseStatsRequest
	(*DatabaseStatsResponse)(nil),     // 5: lightnet.DatabaseStatsResponse
	(*GetRecordRequest)(nil),          // 6: lightnet.GetRecordRequest
	(*GetRecordResponse)(nil),         // 7: lightnet.GetRecordResponse
	(*MerkleProofRequest)(nil),        // 8: lightnet.MerkleProofRequest
	(*MerkleProofResponse)(nil),       // 9: lightnet.MerkleProofResponse
	(*MerkleRootRequest)(nil),         // 10: lightnet.MerkleRootRequest
	(*MerkleRootResponse)(nil),        // 11: lightnet.MerkleRootResponse
	(*VerifyMerkleProofRequest)(nil),  // 12: lightnet.VerifyMerkleProofRequest
	(*VerifyMerkleProofResponse)(nil), // 13: lightnet.VerifyMerkleProofResponse
}
var file_proto_lightnet_proto_depIdxs = []int32{
	0,  // 0: lightnet.HashService.SubmitHash:input_type -> lightnet.HashRequest
	0,  // 1: lightnet.HashService.SubmitHashStream:input_type -> lightnet.HashRequest
	2,  // 2: lightnet.HashService.DebugHash:input_type -> lightnet.DebugHashRequest
	4,  // 3: lightnet.HashService.GetDatabaseStats:input_type -> lightnet.DatabaseStatsRequest
	6,  // 4: lightnet.HashService.GetRecord:input_type -> lightnet.GetRecordRequest
	8,  // 5: lightnet.HashService.GetMerkleProof:input_type -> lightnet.MerkleProofRequest
	10, // 6: lightnet.HashService.GetMerkleRoot:input_type -> lightnet.MerkleRootRequest
	12, // 7: lightnet.HashService.VerifyMerkleProof:input_type -> lightnet.VerifyMerkleProofRequest
	1,  // 8: lightnet.HashService.SubmitHash:output_type -> lightnet.HashResponse
	1,  // 9: lightnet.HashService.SubmitHashStream:output_type -> lightnet.HashResponse
	3,  // 10: lightnet.HashService.DebugHash:output_type -> lightnet.DebugHashResponse
	5,  // 11: lightnet.HashService.GetDatabaseStats:output_type -> lightnet.DatabaseStatsResponse
	7,  // 12: lightnet.HashService.GetRecord:output_type -> lightnet.GetRecordResponse
	9,  // 13: lightnet.HashService.GetMerkleProof:output_type -> lightnet.MerkleProofResponse
	11, // 14: lightnet.HashService.GetMerkleRoot:output_type -> lightnet.MerkleRootResponse
	13, // 15: lightnet.HashService.VerifyMerkleProof:output_type -> lightnet.VerifyMerkleProofResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_lightnet_proto_init() }
func file_proto_lightnet_proto_init() {
	if File_proto_lightnet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lightnet_proto_rawDesc), len(file_proto_lightnet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lightnet_proto_goTypes,
		DependencyIndexes: file_proto_lightnet_proto_depIdxs,
		MessageInfos:      file_proto_lightnet_proto_msgTypes,
	}.Build()
	File_proto_lightnet_proto = out.File
	file_proto_lightnet_proto_goTypes = nil
	file_proto_lightnet_proto_depIdxs = nil
}
